### ISSUE TITLE
Update readme to mention which laser pecker this works on

### ISSUE THREAD

**Issue by GloobyBoolga** [mARTin-B78/LaserPecker-Burntest#1]
This project was linked from the LP2 FB group. 
And at least the README.md should say that LP2 will not honour power/speed setting in the gcode provided here.
Ideally the original FB post in the LP2 group should be edited and rephrased to clearly state that it doesn't work.

**Comment by mARTin-B78** [comment]
done

**Comment by GloobyBoolga** [comment]
thanks!
